"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClozePattern = exports.ClozeNoteOL = exports.ClozeNoteSimple = exports.ClozeNoteClassic = void 0;
var ClozeNoteClassic_1 = require("./src/implementation/ClozeNoteClassic");
Object.defineProperty(exports, "ClozeNoteClassic", { enumerable: true, get: function () { return ClozeNoteClassic_1.ClozeNoteClassic; } });
var ClozeNoteSimple_1 = require("./src/implementation/ClozeNoteSimple");
Object.defineProperty(exports, "ClozeNoteSimple", { enumerable: true, get: function () { return ClozeNoteSimple_1.ClozeNoteSimple; } });
var ClozeNoteOL_1 = require("./src/implementation/ClozeNoteOL");
Object.defineProperty(exports, "ClozeNoteOL", { enumerable: true, get: function () { return ClozeNoteOL_1.ClozeNoteOL; } });
var ClozePattern_1 = require("./src/implementation/ClozePattern");
Object.defineProperty(exports, "ClozePattern", { enumerable: true, get: function () { return ClozePattern_1.ClozePattern; } });
